spring:
  datasource:
    url: jdbc:mysql://localhost:3306/financas?useSSL=false&noAccessToProcedureBodies=true
    username: financas
    password: financas
    dbcp2:
      validation-query: SELECT 1
      test-while-idle: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
server:
  port: 8080
  servlet:
    context-path: /financas-1.0
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
